version: '2'
services:
  jenkins:
    image: 'jenkinsci/blueocean'
    ports:
      - '8080:8080'
    volumes:
      - 'jenkins-data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  jenkins-data:
    driver: local